export const RESPONSE_SUCCESS_CODE = 0;

export const HANDLER_IDS = {
  LOGIN: 0,
  REGISTER: 1,
  UPDATE_LOCATION: 2,
  CREATE_GAME: 4,
  JOIN_GAME: 5,
  JOIN_LOBBY: 6,
  CHOICE_CHARACTER: 7,
  SELECT_CHARACTER: 8,
  EARN_CHARACTER: 9,
  CHATTING: 10,
  SKILL: 50,
};
