export const TOTAL_LENGTH = 4;
export const PACKET_TYPE_LENGTH = 1;

export const PACKET_TYPE = {
  PING: 0,
  NORMAL: 1,
  GAME_START: 2,
  LOCATION: 3,
  GAME_END: 4,
  CHATTING: 5,
  MATCHMAKING: 6,
  ATTACK: 40,
  SKILL: 50,
  REMOVESKILL: 51,
};
